language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "iravalon-github"
    token:
      secure: "41438342b89e32e906609052135468b37c801518"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
